### ISSUE TITLE
Nexus VR is Completely Bricking Games for VR Users

### ISSUE THREAD

**Issue by ghost** [TheNexusAvenger/Nexus-VR-Core#1]
I have noticed that after the new [OpenXR update on Roblox](https://devforum.roblox.com/t/vr-updates-openxr-height-scaling-and-floor-tracking/2435150) that the entire VR system is breaking games completely and is unplayable in VR. I can confirm this isn't my doing since I have not updated the script since the most recent update of this.

I am aware that you have [stopped contributing to this project](https://thenexusavenger.io/article/28/ending-my-contributions-to-nexus-vr-character-model), but I was hoping that this would come to someone's attention so that this issue can be resolved.
![image](https://github.com/TheNexusAvenger/Nexus-VR-Core/assets/116863714/83feb6b0-d366-4b2b-aa72-f9b7c6fae9e1)
Correct me if I am incorrect on this, but I hope that this includes the Nexus VR systems. If it isn't, I understand and will hopefully look into seeing what I can do on my end to fix the issues myself if I can.

_Thank you,_
[hunterk1241](https://www.roblox.com/users/35015902/profile)

**Comment by TheNexusAvenger** [comment]
I've seen this posted in several places, but there is no explanation as to what is breaking. Can you provide a video to show how bad it is? Additionally, which headset?

> Correct me if I am incorrect on this, but I hope that this includes the Nexus VR systems. If it isn't, I understand and will hopefully look into seeing what I can do on my end to fix the issues myself if I can.

I need a report of it affecting Self-Driving Simulator to take action. Almost no one uses VR in the game.

**Comment by ghost** [comment]
**I am using the Meta Quest 2 through Virtual Desktop** and it turns out that this issue is a Roblox issue that happens 90% of the time my testing turned out to be just plain luck for it working on non-Nexus VR games. Due to this, it seems that Nexus VR doesn't know what to do and soft-locks the game alongside Roblox's messed-up VR. I tested it on an empty baseplate and the camera is 2D along with the controls being all borked during a test I did today.

I have already made a [bug report for SteamVR breaking Meta Quest 2 functionality to the devforum](https://devforum.roblox.com/t/meta-quest-2-on-steamvr-is-nearly-unplayable/2424413) a long while ago. I am sorry if I wasted your time on this.
